package fajieyefu.com.luoxiang;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table AUDIT_COUNT.
 */
public class AuditCount {

    private Long id;
    private Integer counts;
    private String username;

    public AuditCount() {
    }

    public AuditCount(Long id) {
        this.id = id;
    }

    public AuditCount(Long id, Integer counts, String username) {
        this.id = id;
        this.counts = counts;
        this.username = username;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public Integer getCounts() {
        return counts;
    }

    public void setCounts(Integer counts) {
        this.counts = counts;
    }

    public String getUsername() {
        return username;
    }

    public void setUsername(String username) {
        this.username = username;
    }

}
