package fajieyefu.com.luoxiang;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table REGION.
 */
public class Region {

    private String codeID;
    private String name;
    private String parentID;

    public Region() {
    }

    public Region(String codeID, String name, String parentID) {
        this.codeID = codeID;
        this.name = name;
        this.parentID = parentID;
    }

    public String getCodeID() {
        return codeID;
    }

    public void setCodeID(String codeID) {
        this.codeID = codeID;
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public String getParentID() {
        return parentID;
    }

    public void setParentID(String parentID) {
        this.parentID = parentID;
    }

}
