package fajieyefu.com.luoxiang.db;

import android.database.sqlite.SQLiteDatabase;

import java.util.Map;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.AbstractDaoSession;
import de.greenrobot.dao.identityscope.IdentityScopeType;
import de.greenrobot.dao.internal.DaoConfig;

import fajieyefu.com.luoxiang.bean.UserInfo;
import fajieyefu.com.luoxiang.bean.InventoryClass;
import fajieyefu.com.luoxiang.bean.Inventory;
import fajieyefu.com.luoxiang.bean.AuditCount;
import fajieyefu.com.luoxiang.bean.LastCheckInfo;
import fajieyefu.com.luoxiang.bean.Region;
import fajieyefu.com.luoxiang.bean.LastCheckClueInfo;
import fajieyefu.com.luoxiang.bean.U8HrCt007;

import fajieyefu.com.luoxiang.dao.UserInfoDao;
import fajieyefu.com.luoxiang.dao.InventoryClassDao;
import fajieyefu.com.luoxiang.dao.InventoryDao;
import fajieyefu.com.luoxiang.dao.AuditCountDao;
import fajieyefu.com.luoxiang.dao.LastCheckInfoDao;
import fajieyefu.com.luoxiang.dao.RegionDao;
import fajieyefu.com.luoxiang.dao.LastCheckClueInfoDao;
import fajieyefu.com.luoxiang.dao.U8HrCt007Dao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see de.greenrobot.dao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig userInfoDaoConfig;
    private final DaoConfig inventoryClassDaoConfig;
    private final DaoConfig inventoryDaoConfig;
    private final DaoConfig auditCountDaoConfig;
    private final DaoConfig lastCheckInfoDaoConfig;
    private final DaoConfig regionDaoConfig;
    private final DaoConfig lastCheckClueInfoDaoConfig;
    private final DaoConfig u8HrCt007DaoConfig;

    private final UserInfoDao userInfoDao;
    private final InventoryClassDao inventoryClassDao;
    private final InventoryDao inventoryDao;
    private final AuditCountDao auditCountDao;
    private final LastCheckInfoDao lastCheckInfoDao;
    private final RegionDao regionDao;
    private final LastCheckClueInfoDao lastCheckClueInfoDao;
    private final U8HrCt007Dao u8HrCt007Dao;

    public DaoSession(SQLiteDatabase db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        userInfoDaoConfig = daoConfigMap.get(UserInfoDao.class).clone();
        userInfoDaoConfig.initIdentityScope(type);

        inventoryClassDaoConfig = daoConfigMap.get(InventoryClassDao.class).clone();
        inventoryClassDaoConfig.initIdentityScope(type);

        inventoryDaoConfig = daoConfigMap.get(InventoryDao.class).clone();
        inventoryDaoConfig.initIdentityScope(type);

        auditCountDaoConfig = daoConfigMap.get(AuditCountDao.class).clone();
        auditCountDaoConfig.initIdentityScope(type);

        lastCheckInfoDaoConfig = daoConfigMap.get(LastCheckInfoDao.class).clone();
        lastCheckInfoDaoConfig.initIdentityScope(type);

        regionDaoConfig = daoConfigMap.get(RegionDao.class).clone();
        regionDaoConfig.initIdentityScope(type);

        lastCheckClueInfoDaoConfig = daoConfigMap.get(LastCheckClueInfoDao.class).clone();
        lastCheckClueInfoDaoConfig.initIdentityScope(type);

        u8HrCt007DaoConfig = daoConfigMap.get(U8HrCt007Dao.class).clone();
        u8HrCt007DaoConfig.initIdentityScope(type);

        userInfoDao = new UserInfoDao(userInfoDaoConfig, this);
        inventoryClassDao = new InventoryClassDao(inventoryClassDaoConfig, this);
        inventoryDao = new InventoryDao(inventoryDaoConfig, this);
        auditCountDao = new AuditCountDao(auditCountDaoConfig, this);
        lastCheckInfoDao = new LastCheckInfoDao(lastCheckInfoDaoConfig, this);
        regionDao = new RegionDao(regionDaoConfig, this);
        lastCheckClueInfoDao = new LastCheckClueInfoDao(lastCheckClueInfoDaoConfig, this);
        u8HrCt007Dao = new U8HrCt007Dao(u8HrCt007DaoConfig, this);

        registerDao(UserInfo.class, userInfoDao);
        registerDao(InventoryClass.class, inventoryClassDao);
        registerDao(Inventory.class, inventoryDao);
        registerDao(AuditCount.class, auditCountDao);
        registerDao(LastCheckInfo.class, lastCheckInfoDao);
        registerDao(Region.class, regionDao);
        registerDao(LastCheckClueInfo.class, lastCheckClueInfoDao);
        registerDao(U8HrCt007.class, u8HrCt007Dao);
    }
    
    public void clear() {
        userInfoDaoConfig.getIdentityScope().clear();
        inventoryClassDaoConfig.getIdentityScope().clear();
        inventoryDaoConfig.getIdentityScope().clear();
        auditCountDaoConfig.getIdentityScope().clear();
        lastCheckInfoDaoConfig.getIdentityScope().clear();
        regionDaoConfig.getIdentityScope().clear();
        lastCheckClueInfoDaoConfig.getIdentityScope().clear();
        u8HrCt007DaoConfig.getIdentityScope().clear();
    }

    public UserInfoDao getUserInfoDao() {
        return userInfoDao;
    }

    public InventoryClassDao getInventoryClassDao() {
        return inventoryClassDao;
    }

    public InventoryDao getInventoryDao() {
        return inventoryDao;
    }

    public AuditCountDao getAuditCountDao() {
        return auditCountDao;
    }

    public LastCheckInfoDao getLastCheckInfoDao() {
        return lastCheckInfoDao;
    }

    public RegionDao getRegionDao() {
        return regionDao;
    }

    public LastCheckClueInfoDao getLastCheckClueInfoDao() {
        return lastCheckClueInfoDao;
    }

    public U8HrCt007Dao getu8HrCt007Dao() {
        return u8HrCt007Dao;
    }

}
