package fajieyefu.com.luoxiang.db;

import android.database.sqlite.SQLiteDatabase;

import java.util.Map;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.AbstractDaoSession;
import de.greenrobot.dao.identityscope.IdentityScopeType;
import de.greenrobot.dao.internal.DaoConfig;

import fajieyefu.com.luoxiang.bean.UserInfo;
import fajieyefu.com.luoxiang.bean.InventoryClass;
import fajieyefu.com.luoxiang.bean.Inventory;

import fajieyefu.com.luoxiang.dao.UserInfoDao;
import fajieyefu.com.luoxiang.dao.InventoryClassDao;
import fajieyefu.com.luoxiang.dao.InventoryDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig userInfoDaoConfig;
    private final DaoConfig inventoryClassDaoConfig;
    private final DaoConfig inventoryDaoConfig;

    private final UserInfoDao userInfoDao;
    private final InventoryClassDao inventoryClassDao;
    private final InventoryDao inventoryDao;

    public DaoSession(SQLiteDatabase db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        userInfoDaoConfig = daoConfigMap.get(UserInfoDao.class).clone();
        userInfoDaoConfig.initIdentityScope(type);

        inventoryClassDaoConfig = daoConfigMap.get(InventoryClassDao.class).clone();
        inventoryClassDaoConfig.initIdentityScope(type);

        inventoryDaoConfig = daoConfigMap.get(InventoryDao.class).clone();
        inventoryDaoConfig.initIdentityScope(type);

        userInfoDao = new UserInfoDao(userInfoDaoConfig, this);
        inventoryClassDao = new InventoryClassDao(inventoryClassDaoConfig, this);
        inventoryDao = new InventoryDao(inventoryDaoConfig, this);

        registerDao(UserInfo.class, userInfoDao);
        registerDao(InventoryClass.class, inventoryClassDao);
        registerDao(Inventory.class, inventoryDao);
    }
    
    public void clear() {
        userInfoDaoConfig.getIdentityScope().clear();
        inventoryClassDaoConfig.getIdentityScope().clear();
        inventoryDaoConfig.getIdentityScope().clear();
    }

    public UserInfoDao getUserInfoDao() {
        return userInfoDao;
    }

    public InventoryClassDao getInventoryClassDao() {
        return inventoryClassDao;
    }

    public InventoryDao getInventoryDao() {
        return inventoryDao;
    }

}
