package fajieyefu.com.luoxiang.bean;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table INVENTORY.
 */
public class Inventory {

    private Long id;
    private String cInvCode;
    private String cInvName;
    private String deMoney;
    private String realMoney;
    private String counts;
    private String weight;

    public Inventory() {
    }

    public Inventory(Long id) {
        this.id = id;
    }

    public Inventory(Long id, String cInvCode, String cInvName, String deMoney, String realMoney, String counts, String weight) {
        this.id = id;
        this.cInvCode = cInvCode;
        this.cInvName = cInvName;
        this.deMoney = deMoney;
        this.realMoney = realMoney;
        this.counts = counts;
        this.weight = weight;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getCInvCode() {
        return cInvCode;
    }

    public void setCInvCode(String cInvCode) {
        this.cInvCode = cInvCode;
    }

    public String getCInvName() {
        return cInvName;
    }

    public void setCInvName(String cInvName) {
        this.cInvName = cInvName;
    }

    public String getDeMoney() {
        return deMoney;
    }

    public void setDeMoney(String deMoney) {
        this.deMoney = deMoney;
    }

    public String getRealMoney() {
        return realMoney;
    }

    public void setRealMoney(String realMoney) {
        this.realMoney = realMoney;
    }

    public String getCounts() {
        return counts;
    }

    public void setCounts(String counts) {
        this.counts = counts;
    }

    public String getWeight() {
        return weight;
    }

    public void setWeight(String weight) {
        this.weight = weight;
    }

}
