package fajieyefu.com.luoxiang.bean;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 

import java.util.List;

/**
 * Entity mapped to table INVENTORY_CLASS.
 */
public class InventoryClass {

    private Long id;
    private String cInvCCode;
    private String cInvCName;
    private String standardId;
    private List<Inventory> inventoryDetails;

    public List<Inventory> getInventoryDetails() {
        return inventoryDetails;
    }

    public void setInventoryDetails(List<Inventory> inventoryDetails) {
        this.inventoryDetails = inventoryDetails;
    }

    public InventoryClass() {
    }

    public InventoryClass(Long id) {
        this.id = id;
    }

    public InventoryClass(Long id, String cInvCCode, String cInvCName, String standardId) {
        this.id = id;
        this.cInvCCode = cInvCCode;
        this.cInvCName = cInvCName;
        this.standardId = standardId;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getCInvCCode() {
        return cInvCCode;
    }

    public void setCInvCCode(String cInvCCode) {
        this.cInvCCode = cInvCCode;
    }

    public String getCInvCName() {
        return cInvCName;
    }

    public void setCInvCName(String cInvCName) {
        this.cInvCName = cInvCName;
    }

    public String getStandardId() {
        return standardId;
    }

    public void setStandardId(String standardId) {
        this.standardId = standardId;
    }

}
