package fajieyefu.com.luoxiang.bean;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table PUSH_NEWS_INFO.
 */
public class PushNewsInfo {

    private String pushId;
    private Integer pushType;
    private Integer enableFlag;

    public PushNewsInfo() {
    }

    public PushNewsInfo(String pushId, Integer pushType, Integer enableFlag) {
        this.pushId = pushId;
        this.pushType = pushType;
        this.enableFlag = enableFlag;
    }

    public String getPushId() {
        return pushId;
    }

    public void setPushId(String pushId) {
        this.pushId = pushId;
    }

    public Integer getPushType() {
        return pushType;
    }

    public void setPushType(Integer pushType) {
        this.pushType = pushType;
    }

    public Integer getEnableFlag() {
        return enableFlag;
    }

    public void setEnableFlag(Integer enableFlag) {
        this.enableFlag = enableFlag;
    }

}
