package fajieyefu.com.luoxiang.bean;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table U8_HR_CT007.
 */
public class U8HrCt007 {

    private String ccodeID;
    private String vdescription;
    private String vsimpleName;
    private Integer ilevels;
    private String cpCodeID;

    public U8HrCt007() {
    }

    public U8HrCt007(String ccodeID, String vdescription, String vsimpleName, Integer ilevels, String cpCodeID) {
        this.ccodeID = ccodeID;
        this.vdescription = vdescription;
        this.vsimpleName = vsimpleName;
        this.ilevels = ilevels;
        this.cpCodeID = cpCodeID;
    }

    public String getCcodeID() {
        return ccodeID;
    }

    public void setCcodeID(String ccodeID) {
        this.ccodeID = ccodeID;
    }

    public String getVdescription() {
        return vdescription;
    }

    public void setVdescription(String vdescription) {
        this.vdescription = vdescription;
    }

    public String getVsimpleName() {
        return vsimpleName;
    }

    public void setVsimpleName(String vsimpleName) {
        this.vsimpleName = vsimpleName;
    }

    public Integer getIlevels() {
        return ilevels;
    }

    public void setIlevels(Integer ilevels) {
        this.ilevels = ilevels;
    }

    public String getCpCodeID() {
        return cpCodeID;
    }

    public void setCpCodeID(String cpCodeID) {
        this.cpCodeID = cpCodeID;
    }

}
